### ISSUE TITLE
Elastic: NoNodeAvailableException when executing example query

### ISSUE THREAD

**Issue by voxlogic** [Lambda-3/Stargraph#26]
Folks,

This is a great project and piqued my interest quite a bit. I've been trying to run the example query on the dbpedia dataset as specified in the Readme for this repo.

docker-compose up  (with the specified yml file) works as expected and starts up the elasticsearch and stargraph containers.

However, when executing the example query of "who is the wife of Barack Obama?", elastic returns a nonodeavailableexception. I am guessing it's got something to do with the docker IP here but any pointers would be super helpful. Appreciate all your help.

Cheers,
Sri

Following is the stacktrace:

2017-10-24 02:43:01,798 INFO  [query] Query Engine took 4.079s Response: NoResponse{'Who is the wife of Barack Obama?', mode='NLI'} 
stargraph    | 2017-10-24 02:43:01,799 ERROR [server] Query execution failed: 'Who is the wife of Barack Obama?' on 'dbpedia-2016' 
stargraph    | net.stargraph.StarGraphException: Query Error
stargraph    | 	at net.stargraph.core.query.QueryEngine.query(QueryEngine.java:98)
stargraph    | 	at net.stargraph.server.QueryResourceImpl.query(QueryResourceImpl.java:63)
stargraph    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stargraph    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
stargraph    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
stargraph    | 	at java.lang.reflect.Method.invoke(Method.java:498)
stargraph    | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
stargraph    | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
stargraph    | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
stargraph    | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
stargraph    | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
stargraph    | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
stargraph    | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
stargraph    | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
stargraph    | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
stargraph    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
stargraph    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
stargraph    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
stargraph    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
stargraph    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
stargraph    | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
stargraph    | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
stargraph    | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
stargraph    | 	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
stargraph    | 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
stargraph    | 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
stargraph    | 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
stargraph    | 	at java.lang.Thread.run(Thread.java:745)
stargraph    | Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{PSRDUzJDSQ6v-zws2vnzCw}{elastic}{172.19.0.3:9300}]
stargraph    | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:328)
stargraph    | 	at org.elasticsearch.client.transp

**Comment by leonardossz** [comment]
Thanks for the interest!
Seems that Elastic Search did not start properly. Did you create the indices successfully?
